
spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/moneysense}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
jwt:
    secret: 2A472D4B6150645367556B58703273357638792F423F4528482B4D6251655468
    expiration: 86400000
