
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://containers-us-west-74.railway.app:6579/railway
    password: 03S9EMxd1Pc8gPWDVswy
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
jwt:
    secret: 2A472D4B6150645367556B58703273357638792F423F4528482B4D6251655468
    expiration: 86400000
