spring:
  datasource:
    hikari:
        jdbc-url: jdbc:postgresql://containers-us-west-74.railway.app:6579/railway
        username: postgres
        password: 03S9EMxd1Pc8gPWDVswy
#        da
#    username: postgres
#    url: jdbc:postgresql://containers-us-west-74.railway.app:6579/railway
#    password: 03S9EMxd1Pc8gPWDVswy
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 2A472D4B6150645367556B58703273357638792F423F4528482B4D6251655468
  expiration: 86400000